### ISSUE TITLE
The installer is not responding

### ISSUE THREAD

**Issue by mickours** [arkOScloud/arkos-install#13]
Hi,
I tried several time to run the arkos installer. The problem is that the application freeze on the "Copying Image on /dev/sdcÂ " state.

I don't know if it is related but the character "Â" appear on each field of the choose device wizard.

I tried to find some debug information to provide by using the terminal to run the application but nothing appear...

I run ubuntu(32bits) 13.10.

Thanks!

**Comment by peakwinter** [comment]
Hi Michael,

This is a peculiar error - is there a chance that your system language/locale is something other than English? There was an error about that awhile back but I haven't yet been able to look into it. You might be able to try running from the [Python package](https://pkg.arkos.io/arkos-install-latest.tar.gz) instead to see if that helps.

Sorry for the inconvenience!

**Comment by mickours** [comment]
I tried to run the package but I got the same problem. I am using french language (which is my language ^^) and I think this is the problem like you said.

But I found a workaround using your package: 
Before running the installer set the Locales to default like this:
`export LC_ALL=C`
Then run the installer in the same terminal:
`./Installer.py`

No strange character appear on the UI and It works like a charm :-)

Still something should be done on the code to avoid that...

I'm trying ArkOS right now and It seems pretty cool,
Thanks!

**Comment by peakwinter** [comment]
OK Thanks! I will make sure the next version adequately adjusts for locale differences.

**Comment by peakwinter** [comment]
This should be fixed with the new internationalization framework, but I want to make sure it can be properly tested before closing the issue.

**Comment by mickours** [comment]
Ok I will try this this Week end. I will let you know.

**Comment by peakwinter** [comment]
If you try, make sure you do so with the code from the Github repo and not from the downloads section! :) Thanks.

**Comment by mickours** [comment]
Sorry but the problem is still here... It even freeze earlier: during the downloading (It could be an other issue?)

Maybe you can add a debug mode so I could give you more information or install some locales on your machine to test yourself

**Comment by peakwinter** [comment]
I can't reproduce this after the latest release (0.3.1) so I am closing this for now - if anyone has similar issues feel free to open a new issue. Thanks!
